const author = "Jhill Patodia";
const CDN_PATH = "https://res.cloudinary.com/jaac";
const IMAGE_PATH = "image/upload";
const TRANSFORMATION = "w_480";

function getURL(path, transformation) {
  if(transformation) {
    return `${CDN_PATH}/${IMAGE_PATH}/${TRANSFORMATION}/${path}`;
  } else {
    return `${CDN_PATH}/${IMAGE_PATH}/${path}`;
  }
}

const IMAGES = {
  horses: 'v1567131401/images/jqt9fgbtsdpg92th6pe5.jpg',
  chillam: 'v1567136052/images/jace2arlctbhki1feruz.jpg',
  an_eye_and_river_wave: 'v1567131401/images/ixjt1sci2fyszfthfpwa.png',
  arun_jaitely: 'v1578238938/images/tziygs41cmlotrjru5jf.jpg',
  bamboo_scenery: 'v1567131400/images/hcsjphofpcd2fy8xqeb2.jpg',
  pen_and_ink: 'v1567131398/images/rvsi98ukotnimracbmzw.jpg',
  abstract_faces: 'v1567131398/images/gqbec8adzuc7uathn4u7.png',
  hilly_area: 'v1567131398/images/gawimww17nvwy2m3y3kb.jpg',  
  horse: 'v1578238959/images/fn0tu5jkpoyrhsvlzyuv.jpg',
  old_house: 'v1567131398/images/a72zbhgt7j7fhcldrbzl.jpg',
  mosquito: 'v1567131396/images/ypk0hmnxomcgxylzqmhw.jpg',
  charcoal_monochrome: 'v1578238914/images/ruxstkwbqvws9arrwqkw.jpg',
  bee: 'v1567131396/images/auqmmxsdae8wbgsvgijl.jpg',
  scorpion: 'v1567131396/images/udlthu937fz09xa7y7w5.jpg',
  agile_fox: 'v1567131397/images/shpahpvom77zd8n6uvdo.jpg',
  village_life: 'v1567131400/images/lemcjkaroefbaxdqawfd.jpg',
  last_hug: 'v1578238928/images/yhfcjkxolrzps7zkop6g.jpg',
};

export const data = [
  {
    "sku": 'jaac_001',
    "title": 'Horses',
    "color": 1,
    "order": 1,
    "size": '21x30',
    "medium": 'acrylic paint',
    "category": 'acrylic',
    "surface": 'canvas',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['horses'], false),
    "thumb": getURL(IMAGES['horses'], true),
  },
  {
    "sku": 'jaac_002',
    "title": 'Chillam',
    "color": 1,
    "order": 2,
    "size": '30x24',
    "medium": 'acrylic paint',
    "category": 'acrylic',
    "surface": 'canvas',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['chillam'], false),
    "thumb": getURL(IMAGES['chillam'], true),
  },
  {
    "sku": 'jaac_003',
    "title": 'An eye and river wave',
    "color": 1,
    "order": 3,
    "size": '50x30',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['an_eye_and_river_wave'], false),
    "thumb": getURL(IMAGES['an_eye_and_river_wave'], true),
  },
  {
    "sku": 'jaac_004',
    "title": 'Arun Jaitley',
    "color": 1,
    "order": 4,
    "size": '21x29.7',
    "medium": 'pencil',
    "category": 'pencil',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['arun_jaitely'], false),
    "thumb": getURL(IMAGES['arun_jaitely'], true),
  },
  {
    "sku": 'jaac_005',
    "title": 'Scenery',
    "color": 1,
    "order": 5,
    "size": '34x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['bamboo_scenery'], false),
    "thumb": getURL(IMAGES['bamboo_scenery'], true),
  },
  {
    "sku": 'jaac_006',
    "title": 'Pen and ink',
    "color": 1,
    "order": 6,
    "size": '21x29.7',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['pen_and_ink'], false),
    "thumb": getURL(IMAGES['pen_and_ink'], true),
  },
  {
    "sku": 'jaac_007',
    "title": 'Abstract faces with different emotions',
    "color": 1,
    "order": 7,
    "size": '50x30',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['abstract_faces'], false),
    "thumb": getURL(IMAGES['abstract_faces'], true),
  },
  {
    "sku": 'jaac_008',
    "title": 'Hilly area',
    "color": 1,
    "order": 8,
    "size": '34x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['hilly_area'], false),
    "thumb": getURL(IMAGES['hilly_area'], true),
  },
  {
    "sku": 'jaac_009',
    "title": 'Horse',
    "color": 1,
    "order": 9,
    "size": '30x50',
    "medium": 'charcoal',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['horse'], false),
    "thumb": getURL(IMAGES['horse'], true),
  },
  {
    "sku": 'jaac_010',
    "title": 'Old house',
    "color": 1,
    "order": 10,
    "size": '34x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['old_house'], false),
    "thumb": getURL(IMAGES['old_house'], true),
  },
  {
    "sku": 'jaac_010',
    "title": 'Mosquito',
    "color": 1,
    "order": 11,
    "size": '23x23.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['mosquito'], false),
    "thumb": getURL(IMAGES['mosquito'], true),
  },
  {
    "sku": 'jaac_011',
    "title": 'Way to nowhere',
    "color": 1,
    "order": 12,
    "size": '23x23.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['charcoal_monochrome'], false),
    "thumb": getURL(IMAGES['charcoal_monochrome'], true),
  },
  {
    "sku": 'jaac_012',
    "title": 'Bee',
    "color": 1,
    "order": 13,
    "size": '16x11',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['bee'], false),
    "thumb": getURL(IMAGES['bee'], true),
  },
  {
    "sku": 'jaac_013',
    "title": 'Scorpion',
    "color": 1,
    "size": '16x11',
    "order": 14,
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['scorpion'], false),
    "thumb": getURL(IMAGES['scorpion'], true),
  },
  {
    "sku": 'jaac_014',
    "title": 'An agile fox and a girl',
    "color": 1,
    "order": 15,
    "size": '30x50',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['agile_fox'], false),
    "thumb": getURL(IMAGES['agile_fox'], true),
  },
  {
    "sku": 'jaac_015',
    "title": 'Village life',
    "color": 1,
    "order": 16,
    "size": '34.5x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['village_life'], false),
    "thumb": getURL(IMAGES['village_life'], true),
  },
  {
    "sku": 'jaac_016',
    "title": 'The last hug',
    "color": 1,
    "order": 17,
    "size": '60x60',
    "medium": 'acrylic paint',
    "category": 'canvas',
    "surface": 'canvas',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES['last_hug'], false),
    "thumb": getURL(IMAGES['last_hug'], true),
  },
];
