const author = "Jhill Patodia";
const CDN_PATH = "https://res.cloudinary.com/jaac";
const IMAGE_PATH = "image/upload";
const TRANSFORMATION = "w_480";

function getURL(path, transformation) {
  if(transformation) {
    return `${CDN_PATH}/${IMAGE_PATH}/${TRANSFORMATION}/${path}`;
  } else {
    return `${CDN_PATH}/${IMAGE_PATH}/${path}`;
  }
}

const IMAGES = [
  'v1567131401/images/jqt9fgbtsdpg92th6pe5.jpg',
  'v1567136052/images/jace2arlctbhki1feruz.jpg',
  'v1567131401/images/ixjt1sci2fyszfthfpwa.png',
  'v1567131400/images/hcsjphofpcd2fy8xqeb2.jpg',
  'v1567131398/images/rvsi98ukotnimracbmzw.jpg',
  'v1567131398/images/gqbec8adzuc7uathn4u7.png',
  'v1567131398/images/gawimww17nvwy2m3y3kb.jpg',
  'v1567131398/images/a72zbhgt7j7fhcldrbzl.jpg',
  'v1567131396/images/ypk0hmnxomcgxylzqmhw.jpg',
  'v1567131396/images/auqmmxsdae8wbgsvgijl.jpg',
  'v1567131396/images/udlthu937fz09xa7y7w5.jpg',
  'v1567131397/images/shpahpvom77zd8n6uvdo.jpg',
  'v1567131400/images/lemcjkaroefbaxdqawfd.jpg'
]

export const data = [
  {
    "sku": 'jaac_001',
    "title": 'Horses',
    "color": 1,
    "size": '21x30',
    "medium": 'acrylic paint',
    "category": 'water_color',
    "surface": 'canvas',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[0], false),
    "thumb": getURL(IMAGES[0], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Chillam',
    "color": 1,
    "size": '30x24',
    "medium": 'acrylic paint',
    "category": 'water_color',
    "surface": 'canvas',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[1], false),
    "thumb": getURL(IMAGES[1], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'An eye and river wave',
    "color": 1,
    "size": '50x30',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[2], false),
    "thumb": getURL(IMAGES[2], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Scenery',
    "color": 1,
    "size": '34x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[3], false),
    "thumb": getURL(IMAGES[3], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Pen and ink',
    "color": 1,
    "size": '21x29.7',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[4], false),
    "thumb": getURL(IMAGES[4], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Abstract faces with different emotions',
    "color": 1,
    "size": '50x30',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[5], false),
    "thumb": getURL(IMAGES[5], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Hilly area',
    "color": 1,
    "size": '34x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[6], false),
    "thumb": getURL(IMAGES[6], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Old house',
    "color": 1,
    "size": '34x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[7], false),
    "thumb": getURL(IMAGES[7], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Mosquito',
    "color": 1,
    "size": '23x23.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[8], false),
    "thumb": getURL(IMAGES[8], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Bee',
    "color": 1,
    "size": '16x11',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[9], false),
    "thumb": getURL(IMAGES[9], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Scorpion',
    "color": 1,
    "size": '16x11',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[10], false),
    "thumb": getURL(IMAGES[10], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'An agile fox and a girl',
    "color": 1,
    "size": '30x50',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[11], false),
    "thumb": getURL(IMAGES[11], true),
  },
  {
    "sku": 'jaac_001',
    "title": 'Village life',
    "color": 1,
    "size": '34.5x27.5',
    "medium": 'water_color',
    "category": 'water_color',
    "surface": 'chart paper',
    "artwork": 'original',
    "description": 'NA',
    "artist": author,
    "src": getURL(IMAGES[12], false),
    "thumb": getURL(IMAGES[12], true),
  },
]
